# Generated by Django 6.0.1 on 2026-02-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="cached_message_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
