# Generated by Django 6.0.1 on 2026-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="vaccines",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="visit_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
