# Generated by Django 6.0.1 on 2026-02-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_visit_vaccines_alter_visit_visit_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="vaccines",
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=100)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Given", "Given"),
                            ("Missed", "Missed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("given_at", models.DateField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="api.patient",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_vaccines",
                        to="api.visit",
                    ),
                ),
            ],
        ),
    ]
