# Generated by Django 6.0.1 on 2026-02-17 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_patient_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True, help_text="X-Ray, MRI, CT, etc.", max_length=50
                    ),
                ),
                (
                    "findings",
                    models.TextField(
                        blank=True, help_text="Detailed findings from the scan."
                    ),
                ),
                (
                    "impression",
                    models.TextField(
                        blank=True, help_text="Overall impression or conclusion."
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_analysis",
                        to="api.attachment",
                    ),
                ),
            ],
        ),
    ]
