# Generated by Django 6.0.1 on 2026-02-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_scanresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="api.chatsession",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="api.visit",
            ),
        ),
    ]
